/* eslint-disable @next/next/no-img-element */
import { ArrowRight, Check } from "lucide-react";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";
import { DEFAULT_WHATSAPP_URL } from "../content";

export default function AboutPage() {
  return <main className="inner-page"><SiteHeader dark /><section className="about-page-hero"><div><small>ABOUT PRIVATE EPHESUS</small><h1>Local knowledge.<br /><em>Personally shared.</em></h1><p>A Kusadasi-based team of licensed guides and dedicated drivers, creating private shore days since 2010.</p></div><img src="/images/ephesus-guide-about-v2.webp" alt="A local Ephesus guide with private guests" /></section><section className="about-manifesto"><small>OUR POINT OF VIEW</small><h2>The monument matters.<br />So does <em>the person beside you.</em></h2><div><p>Ephesus is extraordinary on its own. Yet the stories, questions and quiet details revealed by a gifted guide turn a visit into something personal.</p><p>PrivateEphesusTours is operated by Iglesias Tour Travel Agency under TÜRSAB licence 10772. We work with licensed local guides, separate professional drivers and private air-conditioned vehicles.</p></div></section><section className="about-promises"><article><span>01</span><h3>Truly private</h3><p>No mixed groups and no flag to follow. Only your party and your guide.</p></article><article><span>02</span><h3>Ship aware</h3><p>Every route is planned backwards from your all-aboard time.</p></article><article><span>03</span><h3>Transparent</h3><p>Clear group prices, no deposit and no marked-up museum tickets.</p></article><article><span>04</span><h3>Flexible</h3><p>Interests, mobility and pace shape the experience in real time.</p></article></section><section className="about-license"><div><small>LICENSED & ACCOUNTABLE</small><h2>TÜRSAB<br /><em>10772.</em></h2></div><ul><li><Check /> Iglesias Tour Travel Agency</li><li><Check /> Licensed local tour guides</li><li><Check /> Local expertise since 2010</li><li><Check /> 24/7 WhatsApp assistance</li></ul><a href={DEFAULT_WHATSAPP_URL} target="_blank" rel="noreferrer">Speak with our local team <ArrowRight /></a></section><SiteFooter /></main>;
}
